# SNAPSHOT build workflow
# 
# Every time a change is made on any branch, a SNAPSHOT maven build is triggered,
# which compiles the current change and deploys the resulting SNAPSHOT artifact,
# provided a plugin is included in the pom.xml to deploy the artifact.
#
# Prerequisites:
# - Use of the artifactory-maven-plugin plugin.
# - User of the artifactory stored in the secrets under ARTIFACTORY_USERNAME
# - Token of the user of the artifactory stored in the secrets under ARTIFACTORY_TOKEN
#
# This job is triggered with every change.

name: Run snapshot build-job

on:
  push:
    branches: [ "**" ]

jobs:
  build-snapshot:

    name: SNAPSHOT build-job
    runs-on: ubuntu-latest

    steps:
      - run: echo "CI=$CI"
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{"id": "devtime-sites", "username": "${{ secrets.MAVEN_SITE_USER }}", "password": "${{ secrets.MAVEN_SITE_PASSWORD }}"}, { "id": "releases-repo", "username": "${{ secrets.ARTIFACTORY_USERNAME }}", "password": "${{ secrets.ARTIFACTORY_TOKEN }}" }, { "id": "snapshots-repo", "username": "${{ secrets.ARTIFACTORY_USERNAME }}", "password": "${{ secrets.ARTIFACTORY_TOKEN }}" }]'
          repositories: '[{ "id": "releases-repo", "name": "devtime-release", "url": "https://devtime.jfrog.io/artifactory/devtime-release/", "releases.enabled": "true", "snapshots.enabled": "false" }, { "id": "snapshots-repo", "name": "devtime-snapshot", "url": "https://devtime.jfrog.io/artifactory/devtime-snapshot/", "releases.enabled": "false", "snapshots.enabled": "true" }]'
      - name: Build with Maven
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          MAVEN_SITE_URL: ${{ secrets.MAVEN_SITE_URL }}
        run: mvn -B -DCI=true deploy --file pom.xml
